version: '3.8'
services:
  frontend:
    image: tu-imagen-frontend
    ports:
      - "80:80"
    networks:
      - backend-network
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: cubremochilas
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql-data:
