version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
    ports:
      - "80:80"
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network

  balancer:
    build:
      context: ../balancer
    depends_on:
      - mysql
    networks:
      - backend-network

  api:
    build:
      context: ../api
    depends_on:
      - balancer
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yazmin
      MYSQL_DATABASE: cubremochilas
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql-data:
